services:
    postgres:
        image: postgres:16-alpine
        container_name: bookNest-db
        environment:
            POSTGRES_DB: booknest
            POSTGRES_USER: booknest
            POSTGRES_PASSWORD: booknest
        ports:
            - "5432:5432"
