spring.application.name=bookNest

spring.datasource.url=jdbc:postgresql://localhost:5432/booknest
spring.datasource.username=booknest
spring.datasource.password=booknest123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true